name: PHP Lint

on:
  pull_request:
    branches:
      - master

jobs:
  isValidPHP:
    runs-on: [ubuntu-latest]
    name: Lint-PHP
    steps:
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.0
